name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: install stgit
        shell: bash
        run: |
          sudo apt-get install -y stgit
          git config --global user.name "Chanwit Kaewkasi"
          git config --global user.email "chanwit@gmail.com"
      - name: build
        shell: bash
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          TAG=$(cat VERSION)
          mkdir build/
          cd build/
          git clone https://github.com/k0sproject/k0s
          cd k0s
          git checkout -b build v0.8.1
          stg init
          stg import -s ../../patches/series

          make EMBEDDED_BINS_BUILDMODE=fetch
          docker login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD
          docker build -t quay.io/chanwit/ekz:$TAG .
          docker push quay.io/chanwit/ekz:$TAG
          docker logout quay.io
